const data = [
  {
    name: 'ABC',
    roll: '1',
    regNumber: '111',
    attendance: '100',
    guardian: 'ABC',
    guardianPhone: '0123456789',
    img: 'https://www.w3schools.com/howto/img_avatar.png',
  },
  {
    name: 'DEF',
    roll: '2',
    regNumber: '222',
    attendance: '100',
    guardian: 'DEF',
    guardianPhone: '0123456789',
    img: 'https://www.w3schools.com/howto/img_avatar.png',
  },
  {
    name: 'DEF3',
    roll: '2',
    regNumber: '222',
    attendance: '100',
    guardian: 'DEF',
    guardianPhone: '0123456789',
    img: 'https://www.w3schools.com/howto/img_avatar.png',
  },
  {
    name: 'DEF4',
    roll: '2',
    regNumber: '222',
    attendance: '100',
    guardian: 'DEF',
    guardianPhone: '0123456789',
    img: 'https://www.w3schools.com/howto/img_avatar.png',
  },{
    name: 'DEF46',
    roll: '2',
    regNumber: '222',
    attendance: '100',
    guardian: 'DEF',
    guardianPhone: '0123456789',
    img: 'https://www.w3schools.com/howto/img_avatar.png',
  },
  {
    name: 'DEF33',
    roll: '2',
    regNumber: '222',
    attendance: '100',
    guardian: 'DEF',
    guardianPhone: '0123456789',
    img: 'https://www.w3schools.com/howto/img_avatar.png',
  },
];

export default data;
